//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MakeId { get; set; }
        public Nullable<int> CarModelId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> EngineCapacity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<bool> IsInGarage { get; set; }
    
        public virtual CarModels CarModels { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Makes Makes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
